[package]
name = "insuirance"
edition = "2024.beta"

[dependencies]
deepbook_predict = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/predict", rev = "predict-testnet-4-16" }
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "predict-testnet-4-16" }

[addresses]
insuirance = "0x0"

[environments]
testnet = "0xeb6d56e69e5687ab1a35d05b079a51886539ddd625ba0764e562119ed40c05c4"
